### ISSUE TITLE
Button number persist on Firefox

### ISSUE THREAD

**Issue by FrenzyExists** [imhalid/scrimba-calculator-challenge#1]
TL;DR it seems that the button arrows persist in Firefox as seen here:
![image](https://user-images.githubusercontent.com/47986470/159517270-e9312f3b-5e98-4e09-860a-b8ee3b807f1d.png)

Solution:

```CSS
/* Firefox */
input[type=number] {
    -moz-appearance: textfield;
}
```
